#!/bin/bash

ip addr flush dev eth4
brctl addbr br0
ip tuntap add tap0 mode tap multi_queue
brctl addif br0 tap0
brctl addif br0 eth4
ip link set tap0 up
ip link set eth4 up
ifconfig br0 192.168.4.1 netmask 255.255.255.0 up

