#!/bin/bash
set -x

export KHDIR=/home/jmcadden/debirf/builds/kittyhawk
sudo kexec -l $KHDIR/vmlinuz-3.16.0-4-amd64 --initrd=$KHDIR/debirf-minimal_jessie_3.16.0-4-amd64.cgz --append='quiet console=ttyS1,115200n8 ro single'
sudo kexec -e
